name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node dependencies
      if: always()
      run: npm install
    - name: Run all tests
      if: always()
      run: npm test
    - name: Notify on failure
      if: failure()
      run: echo 'run "npm test" to see/fix errors locally'